PERMISSION_CODES = [
    "lesson:create",
    "lesson:view_all",
    "lesson:export",
    "exercise:create",
    "exercise:view_all",
    "material:upload",
    "material:view_public",
    "material:publish_public",
    "material:view_all",
    "material:manage_all",
    "course:create",
    "course:view_all",
    "course:manage_all",
    "class:manage",
    "class:view_all",
    "class:manage_all",
    "class:join",
    "assignment:manage",
    "assignment:view_all",
    "assignment:submit",
    "assignment:grade",
    "question:view_all",
    "admin:user_manage",
    "admin:role_manage",
    "admin:content_manage",
    "log:view",
    "review:manage",
]

ROLE_PERMISSIONS = {
    "admin": [
        "admin:user_manage",
        "admin:role_manage",
        "admin:content_manage",
        "log:view",
    ],
    "teaching_manager": [
        "lesson:view_all",
        "lesson:export",
        "exercise:view_all",
        "material:upload",
        "material:publish_public",
        "material:view_all",
        "course:create",
        "course:view_all",
        "course:manage_all",
        "class:manage",
        "class:view_all",
        "class:manage_all",
        "assignment:manage",
        "assignment:view_all",
        "assignment:grade",
        "question:view_all",
        "log:view",
        "review:manage",
    ],
    "teacher": [
        "lesson:create",
        "lesson:export",
        "exercise:create",
        "material:upload",
        "course:create",
        "class:manage",
        "assignment:manage",
        "assignment:grade",
    ],
    "student": [
        "class:join",
        "assignment:submit",
        "material:view_public",
    ],
    "pending_teacher": [],
    "operator": ["material:upload"],
}
